const mongose=require('mongoose')
const itemsscema=new mongose.Schema({
        useremail:{
        type:String,
        required:true,
        },
        email:{
            type:String,
            required:true,
        },
        productid:{
            type:String,
            required:true,
        },
        price:{
            type:String,
            required:true,
        },
        productname:{
            type:String,
            required:true,
        },
        Contact:{
            type:Number,
            required:true,
        },
        Contact2:{
            type:Number,
            required:true,
        },
        address:{
            type:String,
            required:true,
        },
        productimage:{
            type:String
        },
        size:{
            type:String
        },
        date:{
            type:Date,
            default:Date.now()
        },
        trackorder:{
            type:String,
            default:"underprocess"
        },
        paymentmethod:{
            type:String,
            default:'COD'
        }
    })
    
module.exports=mongose.model('customerhistory',itemsscema)